//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "result_side")]
pub enum ResultSide {
    #[sea_orm(string_value = "ongoing")]
    Ongoing,
    #[sea_orm(string_value = "white_wins")]
    WhiteWins,
    #[sea_orm(string_value = "black_wins")]
    BlackWins,
    #[sea_orm(string_value = "draw")]
    Draw,
    #[sea_orm(string_value = "abandoned")]
    Abandoned,
}

#[derive(Debug, Clone, PartialEq, Eq, DeriveActiveEnum, EnumIter, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "game_variant")]
pub enum GameVariant {
    #[sea_orm(string_value = "standard")]
    Standard,
    #[sea_orm(string_value = "chess960")]
    Chess960,
    #[sea_orm(string_value = "three_check")]
    ThreeCheck,
    #[sea_orm(string_value = "blitz")]
    Blitz,
    #[sea_orm(string_value = "rapid")]
    Rapid,
    #[sea_orm(string_value = "classical")]
    Classical,
}


#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, DeriveEntityModel)]

#[sea_orm(table_name = "game", schema_name = "smdb")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub white_player: Uuid,
    pub black_player: Uuid,
    #[sea_orm(column_type = "Text")]
    pub fen: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub pgn: Json,
    pub result: Option<ResultSide>,
    pub variant: GameVariant,
    pub started_at: DateTimeWithTimeZone,
    pub duration_sec: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::WhitePlayer",
        to = "super::player::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    WhitePlayer,
    #[sea_orm(
        belongs_to = "super::player::Entity",
        from = "Column::BlackPlayer",
        to = "super::player::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    BlackPlayer,
}

impl Related<super::player::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WhitePlayer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
